config/routes.rb
LR::Application.routes.draw do
  resources :posts
  resources :comments

  get "users/index"
  get "users/show/:id" => "users#show"
  get 'follow' => 'users#follow'
  get 'unfollow' => 'users#unfollow'
  get 'like' => 'users#like'
  get 'unlike' => 'users#unlike'
  devise_for :users

  get "home/index"

  authenticated :user do
    root :to => "home#index"
  end
  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end










end

app/models/comments.rb
class Comments < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  acts_as_likeable
  include PublicActivity::Model
  tracked
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
  include PublicActivity::Model
  tracked
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "avatar/missing.jpg"
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  acts_as_likeable
  include PublicActivity::Model
  tracked
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  has_many :posts
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "50x50>" }, :default_url => "avatar/missing.jpg"
  validates_attachment_content_type :avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  acts_as_follower
  acts_as_followable
  acts_as_liker
  acts_as_likeable
  acts_as_mentionable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  include PublicActivity::StoreController
  hide_action :current_user


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit( :email, :name, :password, :password_confirmation, :current_password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :avatar, :name, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :destroy]
  def create
    @post = Post.find(params[:comments][:post_id])
    @comment = Comments.new(comments_params)
    @comment.user_id = @post.user_id
    @comment.save
    @comment.create_activity :create, owner: current_user
    redirect_to @post
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def comments_params
    params.require(:comments).permit(:post_id, :user_id, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    unless user_signed_in?
      redirect_to new_user_session_path
    else
      @post = Post.new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @posts = Post.all
    respond_with(@posts)
  end

  def show
    @comment = Comments.new
    @comments = Comments.where(post_id: @post.id).all
    respond_with(@post)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.save
    @post.create_activity :create, owner: current_user
    respond_with(@post)
  end

  def update
    @post.update(post_params)
    respond_with(@post)
  end

  def destroy
    @post.destroy
    respond_with(@post)
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:user_id, :content, :avatar)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def show
    @user = User.find(params[:id])
    @activities = PublicActivity::Activity.order("created_at desc").where(owner_id: current_user.id, owner_type: "User")
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end


  def follow
    @user = User.find(params[:user])
    current_user.follow!(@user)
  end
  def unfollow
    @user = User.find(params[:user])
    current_user.unfollow!(@user)
  end

  def like
    if params[:likeable_type] == "Post"
      @likeable = Post.find(params[:likeable_id])
    else
      @likeable = Comment.find(params[:likeable_id])
    end
    current_user.like!(@likeable)
  end

  def unlike
    if params[:likeable_type] == "Post"
      @likeable = Post.find(params[:likeable_id])
    else
      @likeable = Comment.find(params[:likeable_id])
    end
    current_user.unlike!(@likeable)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
.row
  = image_tag comment.user.avatar.url, class: 'profile'
  = comment.user.name
  %div
    = comment.content

app/views/home/index.html.haml
= render 'posts/form'

app/views/layouts/application.html.haml
!!!
/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
/[if lt IE 7 ] <html class="ie6" lang="en">
/[if IE 7 ] <html class="ie7" lang="en">
/[if IE 8 ] <html class="ie8" lang="en">
/[if IE 9 ] <html class="ie9" lang="en">
/ [if (gt IE 9)|!(IE)]>
%html.no-js{:lang => "en"}
  / <![endif]
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    / Uncomment to make IE8 render like IE7
    / <meta http-equiv="X-UA-Compatible" content="IE=7" />
    / Set the viewport width to device width for mobile
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Untitled"
    = stylesheet_link_tag    "application"
    = javascript_include_tag :modernizr
    = csrf_meta_tags
  %body
    /[if lt IE 10]<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    
    = render "shared/nav"
    
    %main.container
      = yield
    = javascript_include_tag "application"

app/views/posts/_form.html.haml
= form_for(@post) do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :user_id
    %br/
    = f.hidden_field :user_id, value: @current_user.id
  .field
    = f.label :content
    %br/
    = f.text_area :content
  = f.file_field :avatar
  .actions
    = f.submit

app/views/posts/edit.html.haml
%h1 Editing post
= render 'form'
= link_to 'Show', @post
|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts
%table
  %thead
    %tr
      %th User
      %th Content
      %th
      %th
      %th
  %tbody
    - @posts.each do |post|
      %tr
        %td= post.user_id
        %td= post.content
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post
= render 'form'
= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice
.user-box
  = image_tag @post.user.avatar.url(:thumb), class: 'profile small'
  = link_to @post.user.name, "/users/show/#{@post.user.id}"
%p
  - unless @post.avatar.url == "avatar/missing.jpg"
    = image_tag @post.avatar.url(:thumb), class: 'profile small'
  = @post.content
= render 'shared/like_form', likeable: @post
= link_to pluralize(@comments.count, 'comment'), @post, class: 'comments'
= render 'shared/form'
%ul
  - @comments.each do |comment|
    %li
      = render 'shared/like_form', likeable: comment
      = image_tag comment.user.avatar.url(:thumb), class: 'profile small'
      = comment.content

app/views/shared/_follow.html.haml
= button_to "Follow", follow_path(user: user.id) , remote: true, method: :get , class: "small button"

app/views/shared/_follow_form.html.haml
- if current_user!= user
  %div{:class => "user-#{user.id}"}
    #follow_form
      - if current_user.follows?(user)
        = render 'shared/unfollow', user: user
      - else
        = render 'shared/follow', user: user

app/views/shared/_form.html.haml
= form_for @comment, url: comments_path do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2
        = pluralize(@comment.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @comment.errors.full_messages.each do |msg|
          %li= msg
  = f.hidden_field :post_id, value: @post.id
  .field
    = f.text_area :content
  .actions
    = f.submit class: 'small button'

app/views/shared/_like.html.haml
= link_to "like", like_path(likeable_id: likeable.id, likeable_type: likeable.class) , remote: true, method: :get , class: "like"

app/views/shared/_like_form.html.haml
- if user_signed_in?
  #like_form
    - if current_user.likes?(likeable)
      = render 'shared/unlike', likeable: likeable
    - else
      = render 'shared/like', likeable: likeable

app/views/shared/_nav.html.haml
.container
  .row
    / %nav{"data-options" => "sticky_on: large", "data-topbar" => "", :role => "navigation"}
    %nav{:role => "navigation"}
      %a{:href => "#"} The nav
      - if user_signed_in?
        = link_to "Log out", destroy_user_session_path, method: "delete"

app/views/shared/_unfollow.html.haml
= button_to "UnFollow", unfollow_path(user: user.id), remote: true, method: :get , class: 'small button'

app/views/shared/_unlike.html.haml
= link_to "Unlike", unlike_path(likeable_id: likeable.id, likeable_type: likeable.class ), remote: true, method: :get , class: 'unlike'

app/views/users/index.html.haml
%h1 Users#index
%p Find me in app/views/users/index.html.erb

app/views/users/show.html.haml
%h1 Users#show
%p Find me in app/views/users/show.html.erb
.right
  - if user_signed_in?
    = render 'shared/follow_form' , user: @user
%span.left
  %h4= @user.name
%br/
%br/
%section
  %h3 Recent Activity
  - if @activities.count
    - @activities.each do |activity|
      .activity
        - if activity.trackable_type == "Comments"
          Comment:
          \#{activity.trackable.content}
        - else
          Post:
          \#{activity.trackable.content}
  - else
    %h3 There is no activity